on:
  push:
    branches:
      - main
name: Publish Docs
jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'stuartwdouglas/ftl-charts'
          token: '${{ secrets.FTL_CHARTS_TOKEN }}'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: .ftl
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config pull.rebase true
      - name: Copy Charts
        run: |
          cp -r .ftl/charts/ charts/
          git add charts
          git commit -a -m "Update charts"
      - name: Init Hermit
        uses: cashapp/activate-hermit@v1.1.3
        with:
          working-directory: .ftl
      - name: repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add goharbor https://helm.goharbor.io

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.FTL_CHARTS_TOKEN }}"


